config/routes.rb
Rails.application.routes.draw do
  
  resources :tasks, :users, :colors

end

app/models/color.rb
class Color < ActiveRecord::Base

	belongs_to :user

end

app/models/task.rb
class Task < ActiveRecord::Base

	belongs_to :user

	scope :incomplete, -> { where(completed: false) }

	validates_presence_of :title

end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :tasks
	has_many :colors
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/colors_controller.rb
class ColorsController < ApplicationController

	respond_to :json

	def index
		@colors = Color.all
	end

	def create
		@color = Color.new(color_params)
		if @color.save
			render @color
		else
			render nothing: true
		end
	end

	private

	def color_params
		params.require(:color).permit(:name)
	end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

	def index
		@tasks = Task.all
		respond_to do |format|
			format.js
			format.html
		end
	end

	def create
		@tasks = Task.all
		@task = Task.new(task_params)
		if @task.save
			# respond_to do |format|
			# 	format.js {render json: @task}
			# 	format.html {redirect_to tasks_path}
			# end
			render :index
		else
			# respond_to do |format|
			# 	format.js {render plain "0"}
			# 	format.html {render :index}
			# end
			render nothing: true
		end
	end

	def update
		@task = Task.find(params[:id])
		if @task.update_attributes(task_params)
			respond_to do |format|
				format.js {render json: @task}
				format.html {redirect_to tasks_path}
			end
		else
			# format.js { render plain: "Failed to update"}
			respond_to do |format|
				format.js { render plain: "0" }
				format.html { redirect_to tasks_path, notice: "Failed to update."}
			end
		end
	end

	private

	def task_params
		params.require(:task).permit(:title, :completed, :due_date, :user_id)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	respond_to :json

	def index
		@users = User.all
		respond_to do |format|
			format.json
			format.js
			format.html
		end
	end

	def create
		@user = User.new(user_params)
		if @user.save
			render @user
		else
			render nothing: true
		end
	end

	def show
		@user = User.find(params[:id])
		respond_to do |format|
			format.json
			format.html
		end
	end

	private

	def user_params
		params.require(:user).permit(:name)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/colors/index.html.haml
Colors

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title OnePageList
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

app/views/tasks/index.html.haml
.wrap
	%h1 One Page Task List
	%p
		Add tasks to your list. As you complete a task, mark it complete!
	%br
	%a{'href' => '#', class: ".toggleModal"} Modal
%ul#taskList
	- @tasks.each do |task|
		%li= task.title
		= button_tag 'Remove Task', class: "deleteTask", id: task.id, data: { "task-id" => task.id }
		= link_to 'X', task_path(task), id: "deleteTask", method: :delete, data: {confirm: "Are you sure?"}
		= link_to 'Edit', edit_task_path(task), remote: true



= form_for Task.new, id: "newTask", remote: true do |f|
	= f.text_field :title
	= f.label "User"
	= f.select :user_id, User.all.collect {|u| [ u.name, u.id ]}
	= f.submit "Add"


/ New Modal
.modal


/ Modal
#modal-one-modal{"aria-hidden" => "true"}
	.modal-dialog
		.modal-header
			%h2 Create A New Task
			%a.btn-close{"aria-hidden" => "true", :href => "#"} ×
		.modal-body
			%p Enter your new task below:
			= form_for Task.new, id: "newTask", remote: true do |f|
				= f.text_field :title
				= f.submit "Add Task", class: "btn"
			

app/views/users/index.html.haml
%h1 All Users

- @users.each do |u|
	Name:
	= u.name
	%br
	Tasks:
	= Task.where(user_id: u.id).pluck(:title).first
	%br
	Colors:
	= u.id
	%ul
	- u.colors.each do |color|
		%li= color.name
	%br
	%br


= button_to "Add User", new_user_path, method: "get"

= form_for User.new, id: "newUser", remote: true do |f|
	= f.text_field :name
	= f.submit "Add"

app/views/users/new.html.haml
new.html.haml